---
name: debian-7
parent: debian
iso_url: https://cdimage.debian.org/cdimage/archive/7.11.0/amd64/iso-cd/debian-7.11.0-amd64-netinst.iso
iso_checksum: 62876fb786f203bc732ec1bd2ca4c8faea19d0a97c5936d69f3406ef92ff49bd
preseed_name: preseed-debian-7.cfg
box_name: debian_7_x64_base
