---
name: fedora-25
parent: common
iso_url: http://download.fedoraproject.org/pub/fedora/linux/releases/25/Server/x86_64/iso/Fedora-Server-netinst-x86_64-25-1.3.iso
iso_checksum: 86bc3694f4938382753d1e9536f2140a6c9c1978207766340c679a89509073c7
preseed_name: anaconda-fedora-25-ks.cfg
box_name: fedora_x64_base
boot_command: |
  [
  "<tab> ",
  "inst.ks=http://{{.HTTPIP}}:{{.HTTPPort}}/{{ user `preseed_name`}} ",
  "biosdevname=0 ",
  "net.ifnames=0 ",
  "<enter>"
  ]
