---
name: ubuntu-1610
parent: ubuntu
config_name: ubuntu-1610-step1-json
iso_urls:
- isos/ubuntu-16.10-server-amd64.iso
- http://releases.ubuntu.com/16.10/ubuntu-16.10-server-amd64.iso
iso_checksum: 72b0d421da77f1e0c549b4efe6fc6c184e9909d6792f0d1e59b56d63e9705659
preseed_name: preseed-ubuntu-1610.cfg
box_name: ubuntu_1610_x64_base
